### ISSUE TITLE
Cannot read property 'associate' of undefined

### ISSUE THREAD

**Issue by jgtbz** [Rocketseat/bootcamp-gostack-03#2]
https://github.com/Rocketseat/bootcamp-gostack-03/blob/2ae354b5c1c945d153017a18ccf408f37940727c/src/database/index.js#L21

.map.map não vai funcionar nesse contexto, pois o primeiro não retorna nada...

https://repl.it/repls/MerryEducatedEyestrain

**Comment by jpedroschmitz** [comment]
Fala @jgtbz, poderias exemplificar melhor? Não consegui entender o problema no `map`. São apenas duas formas de resolver a mesma situação, uma como `forEach` e outra com o `map`. Você teve algum problema na execução? 💜

**Comment by rafaellus89** [comment]
Só não funciona nesta situação se o model que está sendo associado ainda não foi inicializado

**Comment by rafaellus89** [comment]
Também tive este problema "Cannot read property 'associate' of undefined" e no meu caso era por que o model que estava sendo associado ainda não tinha sido inicializado.

Estava tentando está associar User com File, mas o File não tinha sido inicializado, então alterei a ordem dos models no array e funcionou.

const models = [User, File] para const models = [File, User]

**Comment by rafaellus89** [comment]
Pode estar faltando um "return this" dentro do método init nos models.

**Comment by jpedroschmitz** [comment]
Closing the issue due to inactivity.
