### ISSUE TITLE
senddMail is not a function

### ISSUE THREAD

**Issue by alanfagner** [Rocketseat/bootcamp-gostack-03#6]
Boa tarde, estava revisando o codigo para melhorar meu aprendizado e encontrei o nome da funcão de enviar email com erro, esta no pacote  

> src/app/jobs/CancellationMail.js 

ele esta sendo chamando como 

` await Mail.senddMail({...`

e deveria chamar 

` await Mail.sendMail({...`

como podemos ver tem um 'd' a mais na hora de chamar a funcão.

**Comment by jpedroschmitz** [comment]
Fala @alanfagner, tudo bem?

Muito obrigado por abrir essa issue 💜 O problema foi corrigido nesse [commit aqui](https://github.com/Rocketseat/bootcamp-gostack-03/commit/1092a3640806c244090b3cd0fbe7e7dfb7e94051).
